// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  features: dynamic(() => import("./Features")),
  hero: dynamic(() => import("./Hero")),
  table: dynamic(() => import("./Table")),
  testimonials: dynamic(() => import("./Testimonials")),
  text: dynamic(() => import("./Text")),
  text_with_border: dynamic(() => import("./TextWithBorder")),
  text_with_image: dynamic(() => import("./TextWithImage")),
  two_images: dynamic(() => import("./TwoImages")),
};
